CREATE TABLE IF NOT EXISTS fights
(
    id varchar(255) NOT NULL,
    event_id varchar(255) NOT NULL,
    red_id varchar(255) NOT NULL,
    blue_id varchar(255) NOT NULL,
    winner_id varchar(255),
    loser_id varchar(255),
    division varchar(255) NOT NULL,
    time_format varchar(255) NOT NULL,
    ending_round integer NOT NULL,
    ending_time interval NOT NULL,
    method varchar(255) NOT NULL,
    details varchar(255),
    referee varchar(255),
    title_fight boolean NOT NULL DEFAULT 'false',
    perf_bonus boolean NOT NULL DEFAULT 'false',
    fight_bonus boolean NOT NULL DEFAULT 'false',
    red_knockdowns integer NOT NULL,
    blue_knockdowns integer NOT NULL,
    red_sig_strikes integer NOT NULL,
    blue_sig_strikes integer NOT NULL,
    red_sig_attempt integer NOT NULL,
    blue_sig_attempt integer NOT NULL,
    red_takedown integer NOT NULL,
    blue_takedown integer NOT NULL,
    red_takedown_attempt integer NOT NULL,
    blue_takedown_attempt integer NOT NULL,
    red_submission integer NOT NULL,
    blue_submission integer NOT NULL,
    red_reversal integer NOT NULL,
    blue_reversal integer NOT NULL,
    red_control interval,
    blue_control interval,
    red_head integer NOT NULL,
    blue_head integer NOT NULL,
    red_head_attempt integer NOT NULL,
    blue_head_attempt integer NOT NULL,
    red_body integer NOT NULL,
    blue_body integer NOT NULL,
    red_body_attempt integer NOT NULL,
    blue_body_attempt integer NOT NULL,
    red_leg integer NOT NULL,
    blue_leg integer NOT NULL,
    red_leg_attempt integer NOT NULL,
    blue_leg_attempt integer NOT NULL,
    red_distance integer NOT NULL,
    blue_distance integer NOT NULL,
    red_distance_attempt integer NOT NULL,
    blue_distance_attempt integer NOT NULL,
    red_clinch integer NOT NULL,
    blue_clinch integer NOT NULL,
    red_clinch_attempt integer NOT NULL,
    blue_clinch_attempt integer NOT NULL,
    red_ground integer NOT NULL,
    blue_ground integer NOT NULL,
    red_ground_attempt integer NOT NULL,
    blue_ground_attempt integer NOT NULL,
    link varchar(255) NOT NULL
)